### ISSUE TITLE
throw cancellation exception from given cancellation token for cancellation rather than RemoveInvocationException

### ISSUE THREAD

**Issue by heejaechang** [Microsoft/vs-streamjsonrpc#67] opened 2017-11-07 20:57 UTC
currently, when InvokeWithCancellationAsync is called, if call is cancelled by cancellation token, it throws RemoteInvocationException rather than cancellation exception from the token given.

since it is StreamJsonRpc which propagate cancellation message to other side, when other side return due to it, it should know exactly why it got back and it has cancellation token in hand.

I think it should call cancellationToken.ThrowIfCancelled() first and then throw new RemoteInvocationException if cancellationtoken is not raised.

**Comment by AArnott** [comment] 2017-11-08 00:47
Dupe of #38

**Closed by AArnott** 2017-11-08 00:47 UTC
