### ISSUE TITLE
Suggestion: JsonRpc message handler extensibility

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vs-streamjsonrpc#50] opened 2017-08-16 19:58 UTC
Sometimes target object may want to handle JsonRpcMessage and do its own processing. Right now there is no way users can do that. 
If users can supply something like IJsonRpcMessageHandler in place of target object, then they would be able to handle the messages themselves. JsonRpc itself can implement the interface too

Here is an example of such interface:
https://devdiv.visualstudio.com/DevDiv/_git/CascadePrototype/pullrequest/80621?_a=files&path=%2FJsonRpc%2FIRpcService.cs

**Comment by AArnott** [comment] 2017-08-17 22:24
I'm curious what value `JsonRpc` provides to such a user that wants to handle the messages themselves. And how much of the `JsonRpc` class's constructor, methods, etc. apply as well.

**Comment by IlyaBiryukov** [comment] 2017-08-18 00:37
```JsonRpc`` value that remains in this scenario is the following: message handling, json serialization and deserialization, sending out invocations and notifications, stream lifetime management (e.g watching for the stream ending). Basically everything but reflection.

The scenario to enable is custom routing, when a client wants to work with JSON RPC messages directly, without StreamJsonRpc reflection.

**Comment by AArnott** [comment] 2017-08-18 01:58
Might this be a dupe of #49 with my latest suggestion on that issue?

**Closed** 2018-02-05 00:09 UTC
