### ISSUE TITLE
Serialize ReflectionTypeLoadException.LoaderExceptions

### ISSUE THREAD

**Issue by tmat** [microsoft/vs-streamjsonrpc#543] opened 2020-09-04 23:55 UTC
Currently when a ReflectionTypeLoadException is throw by a remote service the client gets back RemoteInvocationException that is not very useful:

```
StreamJsonRpc.RemoteInvocationException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync(<Unknown Parameters>)
---> (Remote Exception) {
  "type": "System.Reflection.ReflectionTypeLoadException",
  "message": "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.",
  "stack": "   "...",
  "code": -2146232830,
  "inner": null
} <--- 
```

The LoaderExceptions are not serialized to the client.

Consider special-casing this exception and serialize the LoaderExceptions and make them available from the RemoteInvocationException.

**Comment by AArnott** [comment] 2020-09-04 23:59
Duplicate of #468. The idea is to serialize *all* exception information and even recreate the exception types on the client side where those types exist as inner exceptions.

**Closed** 2020-09-04 23:59 UTC
